apiVersion: v1
kind: Service
metadata:
  name: external-service
  labels: 
    app: external-service
spec:
  type: ExternalName
  externalName: database-1.cmyxvx9inxns.us-east-1.rds.amazonaws.com
        


